### ISSUE TITLE
Interested in a library version of ExSync?

### ISSUE THREAD

**Issue by marick** [falood/exsync#45]
I *think* I have a use for the ExSync code where having it be an `Application` doesn't fit. The details are probably not interesting, but briefly: I'm writing a testing-support Phoenix localhost webapp that reloads the `_build` files from an independent Mix project, where the location of that project isn't known at Mix startup time (so can't be put in a `config.exs` file). 

The ExSync code is going to work fine for this. (Thank you!) If you like, I can code my fork so that `falood/exsync` could get pull requests that allow it to be used as either an application or a library. If you don't think that's useful for this project, I won't. My use is, I think, very atypical if not downright weird. Producing mergeable code is more work for me, but I feel I should thank you for exsync by making the offer.

**Comment by axelson** [comment]
Hi @marick, while I can't speak for @falood, I have been doing most of the maintenance on exsync recently. In my opinion, I don't think it makes sense to extend exsync to work as a library (and I could foresee that increasing the amount of maintenance required for exsync). So I think that a fork makes great sense :+1:.

Your project sounds very interesting! Is there somewhere that I can read more about it or follow development?

Slightly off topic but how will the user provide the path to the other mix project? I'm actually working on extending https://github.com/axelson/dep_viz to interpret the compile-times of individual modules and I have a PoC that uses wx to put up a file dialog so the user can provide the path to the `mix.exs` file.

Also, since you're interacting with another mix application I'd suggest you use a different `_build` directory (ElixirLS uses `.elixir_ls/build`), otherwise you will end up with build conflicts.

**Comment by marick** [comment]
Sounds good to me. At least for now, I'm just going to have [dsl_dashboard](https://github.com/marick/dsl_dashboard) get project paths from `config/dev.exs` with a dropdown to pick one of them. Were there to ever be any users, I anticipate they'll be working on a small handful of projects at most, so `dev.exs` is as a convenient place to put the equivalent of `~/.bashrc` or `~/.gitconfig`. 

My purpose is to visualize test modules for [ecto_test_dsl](https://github.com/marick/ecto_test_dsl), so your `dep_viz` looks really interesting!

**Comment by axelson** [comment]
Thanks for the link! That seems like an interesting project and I'll be sure to keep an eye on it.
