### ISSUE TITLE
exsync on umbrella apps

### ISSUE THREAD

**Issue by edman** [falood/exsync#46]
Hello, I followed the instructions and running `iex -S mix exsync` causes the applications in my umbrella app not to start.

I managed to workaround it by adding `:application.start(:exsync)` on my .iex.exs (found that was better than adding the dependency to some mix.exs of the apps in the umbrella).

This has the problem that I no longer get the ExSync output on my console, but the functionality seems to be there.

Is there a better solution that I'm missing?

**Comment by axelson** [comment]
Hmm, I think we should actually change the umbrella application instructions because they are not very composable (i.e. you cannot run a different mix task and still have exsync running). I would recommend adding `:exsync` to one of the apps in your umbrella. Can you explain more about what you like better about adding it to `.iex.exs` instead?

**Comment by axelson** [comment]
Here's a PR with proposed updated instructions: https://github.com/falood/exsync/pull/47

**Comment by axelson** [comment]
Fixed in #47
